# Creating some arrays

We are going to practice creating some arrays. The first method is using numpy's function, linspace:

In [1]:
import numpy as np

In [2]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

You can also use np.arange to create an array of evenly spaced values within a given interval. 

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can also change the step size when using arange.

In [4]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

You can also use np.ones to create an array full of 1's of your chosen shape, passed in using a tuple (aka, when you use parentheses).

In [5]:
np.ones((4, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 1

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct. Write a comment in each cell explaining why the output had a particular shape.

In [7]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
arr_1 + arr_2
#The arrays are different shapes, so this will raise an error

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [8]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))
arr_2 + arr_2
#The first array has a single column, so the shape of the second array will determine the shape,
# and the first array will be broadcasted to match the shape of the second array

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [10]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))
arr_1 + arr_2
# This is similar to the previous example, but both arrays have one dimension with only one entry.
# Thereforek the sum will be a 4x6x5 array, taking the non-one dimension from each array.

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [17]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))
arr_1 + arr_2
# The first array has an extra dimension, making it similar to 4 copies of the second array,
# so the second array will be broadcasted to match the shape of the first array.

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [18]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))
arr_1 + arr_2
# This is similar to the previous example, except that the second array cannot be nested inside the first array,
# so this raises an error.

ValueError: operands could not be broadcast together with shapes (4,3,5) (4,3) 

## Summary operations

**Note that for this cell, you need to have ex_array.npy saved in the same directory as this notebook.**

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [19]:
arr = np.load('ex_array.npy')

In [20]:
arr.mean()

0.8717270073789571

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [21]:
arr.shape

(2, 10, 50, 2000)

In [22]:
arr_across_trials = arr.mean(axis=1)

In [23]:
arr_across_trials.shape

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [34]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [35]:
arr_across_trials.shape

(2, 1, 50, 2000)

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [26]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [27]:
arr_across_trials_and_time.shape

(2, 50)

### Question 2

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced, optional.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

When finished, upload a screenshot of this question onto courseworks.

In [30]:
arr_across_neurons_trials_and_time = arr.mean(axis=(1,2,3))
arr_across_neurons_trials_and_time

array([0.98828779, 0.75516623])

In [37]:
new_arr = arr - arr.mean(axis=(1,2,3), keepdims=True)
new_arr

array([[[[-0.88155214, -0.13827436, -0.92216159, ...,  0.23385509,
           0.86605031, -0.95851623],
         [ 0.75755503,  0.05805767,  0.20632473, ..., -0.60129303,
          -0.84202999, -0.43061892],
         [ 0.28832073,  0.64953224,  0.74248875, ..., -0.71910935,
          -0.10076904, -0.49087812],
         ...,
         [-0.8543101 , -0.8262999 , -0.54180719, ..., -0.54833535,
          -0.34569354,  0.24699028],
         [ 1.4873548 ,  0.70584668,  1.13588681, ...,  1.63072314,
           2.12417725,  0.93197903],
         [-0.25864358,  1.05850998,  0.39130579, ...,  0.75370431,
           1.12210222, -0.08958452]],

        [[-0.17750267, -0.05522537, -0.72890867, ...,  0.32714956,
           0.30793807,  0.24924006],
         [-0.42154193, -0.19955491,  0.10524853, ..., -0.49307566,
          -0.76939124, -0.43324843],
         [-0.10538628, -0.30135353,  0.26236271, ..., -0.08382729,
          -0.52821357, -0.55007082],
         ...,
         [-0.95183856, -0.41724062

## Indexing

Indexing in vectors works just as in lists:

In [38]:
#ignore this cell
#initializing the vectors, matrices, and lists here.
lst_1 = [25, 20, 40, 5]
vec_1 = np.array(lst_1)

lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
mat_1 = np.array(lst_1)
# ignore this cell

In [39]:
vec_1

array([25, 20, 40,  5])

In [40]:
vec_1[0]

25

For matrices and higher-dimensional arrays, a single index selects a single row:

In [41]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
mat_1[0]

array([1, 2])

In [43]:
mat_1[0][1]

2

Instead of using two brackets, you can also separate the row and column index by a comma:

In [44]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [45]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [47]:
vec[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [48]:
vec[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [49]:
vec[:] # What do you think this will do?

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [50]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
mat_1[:,0]

array([1, 3, 5])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [52]:
print(vec)
vec[3:7:2]

[0 1 2 3 4 5 6 7 8 9]


array([3, 5])

We could still leave away the beginning or the end of the slice:

In [53]:
vec[::2]

array([0, 2, 4, 6, 8])

### Question 3
Predict the output of the following commands. After every output, explain in words using a comment why that was the output. Upload a screenshot of this onto courseworks.

In [54]:
vec
# This will be the whole array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
vec[:4]
# The array from the 0th to the 3rd (4-1) element

array([0, 1, 2, 3])

In [56]:
vec[5:9:2]
# The array from the 5th to the 8th (9-1) element, with a step size of 2

array([5, 7])

In [57]:
vec[:7:2]
# The array from the 0th to the 6th (7-1) element, with a step size of 2

array([0, 2, 4, 6])

In [58]:
vec[2::2]
# The array from the 2nd to the final element, with a step size of 2

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [59]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [61]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [63]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [64]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
mat_1 >= 3

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [66]:
mat_1[mat_1 >= 3]

array([3, 4, 5, 6])

### Questions 4
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multiple lines! Upload a screenshot onto courseworks once you are done!

In [67]:
mat_1[(mat_1 >= 2) & (mat_1 <= 4)]

array([2, 3, 4])